import { StationEntity } from "../../modules/wrap/station/station.entity";

export const STATIONS_TEST: StationEntity[] = [
    {
        id: 1,
        code: 'ST000001',
        name: 'Planta',
        altitude: 108,
        longitude: -2.416275,
        latitude: 36.874496,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 2,
        code: 'ST000002',
        name: 'Pechina',
        altitude: 98,
        longitude: -2.446047,
        latitude: 36.919046,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 3,
        code: 'ST000003',
        name: 'Gador',
        altitude: 176,
        longitude: -2.508389,
        latitude: 36.963916,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 4,
        code: 'ST000004',
        name: 'Boticario',
        altitude: 72,
        longitude: -2.390605,
        latitude: 36.867357,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 5,
        code: 'ST000005',
        name: 'Las viudas',
        altitude: 156,
        longitude: -2.378156,
        latitude: 36.889178,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 6,
        code: 'ST000006',
        name: 'Los trancos',
        altitude: 87,
        longitude: -2.280015,
        latitude: 36.850658,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 7,
        code: 'ST000007',
        name: 'Costacabana',
        altitude: 5,
        longitude: -2.387583,
        latitude: 36.837485,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    },
    {
        id: 8,
        code: 'ST000008',
        name: 'El bobar',
        altitude: 11,
        longitude: -2.424824,
        latitude: 36.822050,
        active: 1,
        updated: new Date(),
        created: new Date(),
        description: 'lñaskdfalskdfasldfj',
        units: [],
        image: null,
    }
];